### PR TITLE
add support for RTFs that import images from external files

### PR DESCRIPTION
**Pull request by warren-bank**
ex:
===
  {\field {\*\fldinst import image.WMF}}
  {\field {\*\fldinst import image.EMF}}

where:
======
* "image.WMF" is a relative URL path
* the external files are not read by the library
* a new hook function is added to the "settings" Object
  that is passed to the "RTFJS.Document()" constructor
  * "settings.onImport(relURL, cb)"
  * this hook function is responsible for:
    * reading data from the external file @ "relURL" into a blob
    * mapping the file extension to a "keyword" (ex: "wmetafile")
    * passing this information to the callback function
      * cb({error, keyword, blob, width, height})

demo:
=====
  samples/04_rtf_imports/rtf.html

implication:
=====
- changes return type of Document.render() (Breaking change)
- requires ES6 in its current form

### CODE REVIEW

**Comment by warren-bank** [comment]
this commit contains all the important changes.. and the new sample to demo its usage

**Comment by warren-bank** [comment]
another caveat:
* the code in `rtf.js` contains: `RTFJS._pxToTwips(300)`
  * this hard codes the height of all images to 300px
  * their width is allowed to maintain aspect ratio.. up to the full width of the browser window
* I'm not aware of whether the spec for this RTF import syntax supports embedding width and height
  * it doesn't appear to..
  * if it did, then the value could be read.. parsed.. used
  * if not.. then?
  * ..without giving it any serious thought, I just figured that 300px is adequate in most situations
  * a better option might be to allow the settings passed to the Document constructor to over-ride this value for height
  * ..something to consider

**Comment by zoehneto** [comment]
In terms of ES6: if I haven't missed anything it's only promises and arrow functions. I would say promises are fine as there are simple polyfills available (we could add something to the README since it is required for IE 11 compatability). We could probably replace the arrow functions with normal functions to maintain IE 11 compatability or add a transpile step (or typescript which would be my preference) or we could leave it as is and break IE 11. @tbluemel do you have an opinion on this?

**Comment by warren-bank** [comment]
I was about to replace the arrow functions.. but noticed that some of the inner functions reference `this`. So.. to replace them would mean using the old pattern of `var self = this`.. which is ugly.. and you'd probably mock me for :)

**Comment by zoehneto** [comment]
I really have no strong opinion about this either way, I have been thinking about migrating everything to typescript but haven't had time yet. Lets see what Thomas thinks about it.

**Comment by warren-bank** [comment]
but.. off-hand.. I'd say: Promises, arrow functions, Object literal short-hand `{val}`, Object destructuring, function default values, ...hmm, I think that may be it?

**Comment by zoehneto** [comment]
The problem is that I don't know what people use this library for (or more specifically with which browser). I personally use it for my chrome / firefox extension so it doesn't concern me but there might be people using it in IE 11 who want compatibility with those browsers. In the end it might be a good idea to merge as is and then add a buildstep later on to get compatibility with older browsers.

**Comment by warren-bank** [comment]
what I like to do is to add a `./browser_bundle/` directory.. which includes
* a `package.json`.. with all the dev-dependencies needed to transpile
* a `src/globals.js` entry point
  * imports the important library modules and assigns them to global variables
    * (ex: `windows.foo = require('../foo')`
* exports to: `dist/bundle.js`

**Comment by zoehneto** [comment]
I guess something like that would make sense but lets wait what @tbluemel thinks about it. 

Regarding image size: I guess there is really nothing we can do if there is no image size specified in the RTF. I assume you have to provide a size since otherwise the image will have a size of `nullpx`?

**Comment by warren-bank** [comment]
exactly! ..that was what [this commit](https://github.com/tbluemel/rtf.js/pull/29/commits/3955324019b7763fc975dd61c968f9252c010b18) was all about

it adds a safety net to make sure that if the values are `null`, then at least they get set to `0`
* `null` => Error
* `0` => 0x0 svg image

**Comment by zoehneto** [comment]
But then it also defeats the purpose of having this feature if no one can actually see the image. Maybe it would make sense to make this user configurable in the `onImport` method, at least the user might have an idea what dimensions they want / expect.

**Comment by warren-bank** [comment]
well.. my hard-coded values (ie: width = 100%, height = 300px) make sure that imported images will never be in this situation.

However, before I added this code.. I was encountering this situation.
* 1st: I was seeing Errors being logged to console.. which helped me to identify the cause
* 2nd: I added the safety net.. which prevented the Error.. but resulted in 0-width images
* 3rd: I found a good place to inject sane values for width and height

**Comment by zoehneto** [comment]
My question is just whether it would make sense to have these values user configurable in the onImport method.

**Comment by warren-bank** [comment]
As for the question of how best to allow the user to customize these values.. ??

A hook function that needs to pattern match against the relative URI seems clumsy.. but.. there really is no good solution, unless the values can be embedded directly into the RTF's import tag.

**Comment by zoehneto** [comment]
And the onImport function already loads the data so the user has access to the url there, so I would add an (optional) parameter after keyword and blob.

**Comment by warren-bank** [comment]
agreed.. no harm in giving them the option.. it'd be an easy change

**Comment by zoehneto** [comment]
That would probably make sense, with the user being so deeply involved I could easily see us adding more parameters in the future so an object would make sense.

**Comment by warren-bank** [comment]
ok.. I'll make that change right now; I'll test it before I commit.. shouldn't take more than a few mins..

**Comment by warren-bank** [comment]
ok.. all set

**Comment by warren-bank** [comment]
note: I updated the "sample"
* each of the image files contain a numeric index (0, 1, 2, ..)
* the index is parsed out of the URI and multiplied by 100.. then added to 300
  * 1st image: height = 300
  * 2nd image: height = 400
  * etc..

**Comment by zoehneto** [comment]
Very nice :) I thinks this PR is ready for merging now, let's just wait whether @tbluemel has an opinion on the ES6 part.

**Comment by warren-bank** [comment]
there's another caveat.. that could possibly become an issue

* the "RTFContentLoaded" Event is only fired if the RTF contains import statements
  * it occurs after all the callbacks have been called

* it doesn't fire when:
  * there are no async files to load via the "onImport" hook

* it also doesn't (currently) fire if any of the "onImport" hooks forget to call the callback
  * this could be fixed by adding a timer on each
  * opinion?

**Comment by warren-bank** [comment]
some thoughts..

`async_inflight` and `async_complete` are currently scoped:
* in function `fldinstDestination`
  * in function `RTFJS.Document.prototype.parse`

to make this work, I think I'll need to refactor..
* migrate them to:
  * `RTFJS.Document.prototype.async_inflight_incr`
  * `RTFJS.Document.prototype.async_inflight_decr`
  * `RTFJS.Document.prototype.async_complete`

which would allow `RTFJS.Document.prototype.render` to access this data.
* ex:
  * this.async_complete(true)
* where:
  * the boolean parameter would indicate that it's a special case..
    * not intended to decrement the counter
    * just test if the counter is already zero
      * if so, then fire the Event

**Comment by zoehneto** [comment]
I have to say I'm not the biggest fan of the hole event thing. It would be really great if `RTFJS.Document.prototype.render` returned a promise with the result. You could then check whether there is anything async going on and either chain the dom building it to a `Promise.all()` of the imported images or `Promise.resolve()` with the current code directly.

**Comment by warren-bank** [comment]
actually.. another option.. one that may be much cleaner.. is to make `RTFJS.Document.prototype.render` fire a different Event.

elsewhere in the code.. where all the `inflight` stuff lives.. we can listen for this other Event and run a handler..
* if there are async hooks running, then do nothing
* otherwise, fire `RTFContentLoaded` immediately

**Comment by zoehneto** [comment]
That is also an option but I have to say I'd much prefer the promise option, the events solution is far to hacky for my taste. Also the async tracking (if it is relevant for rendering) logically belongs in `RTFJS.Document` because that is the starting point for parsing and rendering.

**Comment by warren-bank** [comment]
i'm not so sure that would work..
please correct me if i'm wrong, but render basically iterates through an array of functions.. calling each in order

the problem is.. when there's an import:
* we add a function to this array
  * this is a placeholder so the image renders in the correct location within the document
* the function should not be run until after the callback is invoked
  * otherwise, the function references data that is not yet available and throws an Error

it seems that it would be a lot more complicated to handle render being called prematurely..

a simpler solution is to make the user wait until an Event is fired that indicates it's safe to use, which is the current methodology.

the problem is.. this Event should fire for all RTF documents.. not only the "weird" ones.

the more I think about it.. I really like the idea of using a 2nd (internal) Event. It keeps the code loosely coupled.

**Comment by warren-bank** [comment]
mind if I give it a try?

should that be included in this PR.. or should I separate it into a new one?

**Comment by zoehneto** [comment]
Before you get into it: if you stored the promises created in line 1460 in an array on the Document object my Promise.all() solution should work right?

**Comment by warren-bank** [comment]
one sec.. need to check..

**Comment by warren-bank** [comment]
ok.. this is an area of the code that seemed to dead-end for me..

* `fldinstDestination().prototype.parseType()`
  * returns a Promise
  * passes it to:
    * `fieldDestination().prototype.setInst()`
      * the resolved values is assigned to: `this._parsedInst`
        * it appears that this resolved value should be an Object having 2 functions: `{renderFieldBegin, renderFieldEnd}`
          * neither of which appear to ever be called (when I test with `alert()` statements)

* I'm really not familar enough with the internals.. or the render process.. to be the guy to answer this question
* Maybe it could be possible to do something like:
  * `if (inst instanceof Promise) someGlobalArray.push(inst)`
* and then render would wrap itself in a:
  * `Promise.all(someGlobalArray, () => {return this._renderer.buildDom()})`

idk..
to me, this all feels very hacky..
I'm a big fan of the pub-sub model.. (ie: Events)
it's used everywhere.. it's at the very heart of redux..
I find it rather elegant.

**Comment by warren-bank** [comment]
I'm also a big fan of "whatever works" :)
..whichever is simplest to code, and easiest to reason about

but yeah.. this is probably better left for a separate PR
..in a separate branch.. where we can break stuff :)

**Comment by zoehneto** [comment]
I'm just testing it out, just one sec.

**Comment by warren-bank** [comment]
no rush.. i'll go grab another coffee :)

**Comment by zoehneto** [comment]
I have just added the promise solution and I have to say it is really nice :) Also means we don't have to keep track of async_inflight. Do you want me to commit it to this PR ?

**Comment by warren-bank** [comment]
sure.. I'd like to see how you did it.. color me impressed, good sir :)

**Comment by zoehneto** [comment]
Just pushed my changes, I also adapted the examples to the new API.

**Comment by warren-bank** [comment]
I'm really liking what I'm seeing.. just need another few minutes to finish looking it over. Nice!

**Comment by warren-bank** [comment]
ahh.. I was literally just about to ask you about that `catch` statement :)

**Comment by warren-bank** [comment]
Absolutely.. I'm digging it. You were right. I was wrong. That is an elegant solution. Digging it a lot :)

**Comment by zoehneto** [comment]
That is the big downside here, especially since we don't do versioning (as of yet). I should probably tag the current version as 1.0 and add a CHANGELOG when this is merged.

**Comment by warren-bank** [comment]
I'm sure you already tested all of the samples yourself.. but I can also confirm that they're all working perfectly.. locally from this branch.

**Comment by zoehneto** [comment]
What I tested works, though I don't have my full collection of test files here (but I'm not anticipating any big issues since the changes mostly concern the import feature).

**Comment by warren-bank** [comment]
oh.. if there's a test suite, you should definitely add it to the repo.
The npm script to run tests is currently stubbed.

The extent of my testing was to just temporarily replaced the infamous `jquery.binarytransport.js` with my modded version.. and open each of the samples in the browser.

**Comment by zoehneto** [comment]
I just created a changelog and tagged the current master as v1.0 . When I merge this PR I will tag it as 2.0.

**Comment by warren-bank** [comment]
sounds good to me..
when you do so, you may also want to bump the version number in `package.json`..
not that it matters..
not like it's being published to npm anytime soon..
is it? :)

**Comment by warren-bank** [comment]
oh.. that also reminds me..
you may want to fill in the "authors" field in `package.json`..
it was left blank

**Comment by zoehneto** [comment]
There isn't really a test suite, there's just me changing my [chrome extension](https://github.com/zoehneto/chrome-rtf-viewer) and opening a couple hundred files from my hard drive (since chrome extensions can load files from the filesystem directly). Eventually this should be automated but it might be problematic since the files are just scraped from the internet.

**Comment by zoehneto** [comment]
Just added the author to package.json, will also bump the version there. In terms of releasing it on npm there is no real reason not to, other than no one ever requested it :)

**Comment by warren-bank** [comment]
oh.. cool.. that's a handy browser extension

..mental note saved and filed away

**Comment by zoehneto** [comment]
Towards the hole ES6 issue I just pushed a branch which converts the project to typescript. Right now I have only converted rtf.js, the result is the following:
- rtf.js is split into multiple typescript files and then compiled and bundled with rollup into a UMD bundle
- The bundle already contains cptable (part of a node package) and symboltable (part of this project but previously only in the samples folder)
- The UMD output (rtf.bundle.js) maintains compatibility with the current API.

I'm looking to convert emf.js and wmf.js over the next couple of days as well. I will then also add documentation on what scripts need to be loaded externally (jquery and perhaps jquery.svg) and what polyfills will eventually be required for older browsers (for now probably just a promise polyfill).

**Comment by zoehneto** [comment]
Wmf.js is now also converted to typescript.

**Comment by zoehneto** [comment]
The typescript conversion is done, I have created a PR and am now waiting for feedback from @tbluemel .

**Comment by warren-bank** [comment]
You've been busy!

I partially feel that the topic of Typescript is to Javascript developers.. what religion and politics is to a dinner party :) There really are no middle-of-the-road opinions.. people are either passionately for- or against-.. and discussions quickly lead to conflict and name-calling.

Personally, I'm well aware of all the benefits.. static analysis.. which allows for better tooling.. and catching certain classes of bugs before they can be deployed. And yet.. having used it in a handful of projects (ie: ng2 + nativescript).. I have to admit.. I really dislike it. It was a while ago.. and I can't remember exactly what the issues were.. but I do remember spending far too much time fighting the ts transpiler to use 3rd party modules. Left a bad taste.

**Comment by tbluemel** [comment]
I have to admit that the whole architecture isn't entirely clean, and promises probably would help clean up the code and some archaic constructs.  I would still like to at least long-term keep the following two stages somewhat separate:
1. Parsing the file into a set of instructions that can construct the document (or image)
2. Actually rendering the document based on the instructions

So, in the context of this feature, The URL probably should just be passed to some sort of a validation callback in step #1 (to give the api consumer a chance to reject or modify it), but it would essentially just remain stored in the generated instructions until step #2 (and maybe at that point there could be another callback to give the api consumer a chance to custom-build e.g. an appropriate  tag.  I haven't had a chance to look at the changes here, but just some thoughts for you guys ;-)

**Comment by zoehneto** [comment]
I would say the current state still maintains the separation storing the promises in the Document which is the DTO between Parser and Renderer. Also the data returned by the Promises isn't used, the promises are just used to keep track of when all async tasks are finished.

**Comment by zoehneto** [comment]
I have meanwhile merged the typescript branch so I can continue working there and rebased this PR on the current (typescript) master. This should also help to clarify the architectural implications since the modifications are now split into the files `Parser.ts`, `Document.ts` and `DocumentFacade.ts`.

**Comment by zoehneto** [comment]
Actually looking at this split up I think `_asyncTasks` should be moved to `Parser.ts` and Parser.parse() should return a Promise indicating when parsing is complete so the renderer can be invoked.

**Comment by zoehneto** [comment]
The parser now keeps track of all promises internally and just returns one promise indicating when parsing has finished.

**Comment by tbluemel** [comment]
Nice, I like that approach.

**Comment by zoehneto** [comment]
@warren-bank thank you for putting the work into splitting this up and getting this PR ready for merge. I will now add the info to the changelog and package.json .

**Pull request merged**
