### PR TITLE
refactor samples

### PR DESCRIPTION
**Pull request by warren-bank**
the following files are marked as having been modified, though they were not:
* jquery.svg.css
* simplepng.rtf
* jquery.svg.min.js

if I had to guess the cause:
* the files in the repo were probably uploaded with a git client that wasn't configured to normalize EOL markers
* when I cloned, moved the files, re-uploaded, and my git client did normalize their EOL markers.. the contents are seen as having been modified

[docs](https://help.github.com/articles/dealing-with-line-endings/)
* `git config --global core.autocrlf true`

### CODE REVIEW

**Comment by warren-bank** [comment]
the first 2 commits belong to the PR regarding whitespace..
the last commit is unique to this PR.

I know..
PRs should be standalone, but each of these PRs build on each other..
I named my branches PR01, PR02, etc..
they should be evaluated in order.

I'll hold off and give you a chance to evaluate these 2..
since they don't add anything new.

once approved, then I'll start to layer in some changes.

**Comment by zoehneto** [comment]
Looks good, just needs the changes from PR01 and the formatting exlusion for the .common directory.

**Comment by warren-bank** [comment]
ok.. this one is now rebased to build upon the updated PR01

summary: eclint is only being applied to the javascript files in the root directory.. but not recursively into subdirs. This shields both `samples` as well as `node_modules`.

**Comment by warren-bank** [comment]
cool.. you'll also want to:

```bash
git checkout 'gh-pages'
git merge 'master'
git push -u origin 'gh-pages'
```

..so the links in the README are published

**Comment by warren-bank** [comment]
great.. the links are working

now.. on to applying some updates :)

**Comment by tbluemel** [comment]
@zoehneto Looks like you accidentally created a 1.0 release tag?  I don't think we're anywhere close to 1.0 ;-)

**Comment by zoehneto** [comment]
@tbluemel I just declared the current state 1.0 since it works and PR #32 and possibly the typescript branch will introduce breaking api changes which would be semver major. Obviously we are far from feature complete but then I doubt that complete RTF + WMF + EMF is something which can realistically ever be achieved. I hope this is ok with you :)

**Pull request merged**
