### PR TITLE
remove sourcemaps from dist

### PR DESCRIPTION
**Pull request by joeypedicini92**
I was getting this error when building our Ember app after installing the new npm package:
```
> OFFLINE_DEV=true ember serve

Livereload server on http://localhost:49153
'instrument' is imported from external module 'ember-data/-debug' but never used
/Users/jpedicini/Repositories/tricorder/node_modules/combine-source-map/index.js:100
 * @function
     ^

RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at RegExp.[Symbol.match] (native)
    at String.match (native)
    at Object.exports.fromSource (/Users/jpedicini/Repositories/tricorder/node_modules/combine-source-map/node_modules/convert-source-map/index.js:122:19)
    at resolveMap (/Users/jpedicini/Repositories/tricorder/node_modules/combine-source-map/index.js:50:21)
    at Combiner.addFile (/Users/jpedicini/Repositories/tricorder/node_modules/combine-source-map/index.js:110:21)
    at DestroyableTransform.write [as _transform] (/Users/jpedicini/Repositories/tricorder/node_modules/browser-pack/index.js:63:23)
    at DestroyableTransform.Transform._read (/Users/jpedicini/Repositories/tricorder/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/jpedicini/Repositories/tricorder/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/jpedicini/Repositories/tricorder/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/jpedicini/Repositories/tricorder/node_modules/readable-stream/lib/_stream_writable.js:395:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tricorder@1.42.4 offline: `OFFLINE_DEV=true ember serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tricorder@1.42.4 offline script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jpedicini/.npm/_logs/2018-03-28T18_47_48_982Z-debug.log
```

When I would turn off sourcemapping during the ember build the problem went away so it was something to do with bundling the sourcemaps. Then when I rebuilt rtf.js without sourcemaps and turned sourcemapping back on in our app again it worked fine. 

I think best practice is to let client create sourcemap themselves instead of packaging with the sourcemaps.

Here's a PR that turns off sourcemaps and removes them from dist, should be ready to publish (this worked on my end)

Thanks again for all the quick work on this I really appreciate it!

### CODE REVIEW

**Comment by zoehneto** [comment]
Looking at some other projects like @angular etc. they all publish sourcemaps and with the same naming and reference style (`//# sourceMappingURL=RTFJS.bundle.js.map`). This seems logical since you would otherwise have to build every single dependency from source in order to get your sourcemaps. On the other hand it seems like at least webpack simply ignores source maps for everything in node_modules.

I definitely want to keep sourcemaps in the repo for people using it as a script and for development. 

Googling your error message it seems to be one of two issues:
- Spaces or special characters in the path (because the package name is rtf.js): https://github.com/ionic-team/ionic-cli/issues/1020
- The bundle is to large so the regex looking for the sourcemap hits the stack size limit: https://github.com/nodejs/node/issues/759 (and similar issues)

Could you please try to verify which of these is your issue? Without knowing your exact build process this is hard for me to debug. If you are using the ember cli it might also make sense to raise an issue there.

**Comment by joeypedicini92** [comment]
I'll raise an issue with ember-cli as well, but yeah i'm fairly certain its the latter of the two options you presented.

**Comment by joeypedicini92** [comment]
So I switched over to using yarn and I don't get that error anymore...¯\_(ツ)_/¯

**Comment by zoehneto** [comment]
:D fascinating. I'll close this PR for now, if you find anything we can do to fix it with npm please create a new PR.

**Pull request closed without merging**
